apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - HTTP-route.yaml
  - github-secret.yaml
  - service.yaml
  - db
  - hasura
  - kargo
  - auth-secret.yaml
patchesStrategicMerge:
  - patches/deployment.yaml
images:
  - name: ghcr.io/simonbrundin/plan
    newTag: "frontend-1.6.1"
