apiVersion: v1
kind: Service
metadata:
  name: plan-service-dns
spec:
  type: ExternalName
  externalName: plan-service.plan.svc.cluster.local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
