apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - 01-schema.sql=schema.sql
      - 02-seed-data.sql=seed-data.sql
