apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - db/postgres.yaml
  - hasura.yaml
configMapGenerator:
  - name: postgres-init-scripts
    files:
      - db/schema.sql
      - db/seed-data.sql